version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - ./_docker_volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
      interval: 3s
      timeout: 3s
      retries: 3

  backend:
    depends_on:
      postgres:
        condition: service_healthy
