version: "3.9"

services:
  postgres:
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    build:
      context: .
    command: tail -f /dev/null
    volumes:
      - ./backend:/app/backend
      - ./manage.py:/app/manage.py
    ports:
      - "8000:8000"
    env_file:
      - .env
